name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/common-ground-new-build:latest

    - name: Run health check
      run: |
        docker run -d -p 3000:3000 --name common-ground-new-build ${{ secrets.DOCKER_HUB_USERNAME }}/common-ground-new-build:latest
        sleep 10
        curl -f http://localhost:3000/health || (echo "Health check failed" && exit 1)
        docker stop common-ground-new-build
        docker rm common-ground-new-build
